services:
  web:
    image: ghcr.io/eslam-allam/cpr-extract:0.0.3
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - cpr_net
    deploy:
      resources:
        limits:
          cpus: '0.25' # Max 25% of one core
        reservations:
          cpus: '0.10'

  worker:
    image: ghcr.io/eslam-allam/cpr-extract:0.0.3
    command: ["rq", "worker", "-c", "settings"]
    networks:
      - cpr_net
    # Give the worker the most "muscle"
    deploy:
      resources:
        limits:
          cpus: '1.5'  # Allow it to burst up to 1.5 cores if available
        reservations:
          cpus: '0.75' # Guarantee it at least 75% of one core

  redis:
    image: redis:alpine
    networks:
      - cpr_net
    deploy:
      resources:
        limits:
          cpus: '0.20'
networks:
  cpr_net:
    driver: bridge
